name: Tests
on:
  pull_request:
  schedule:
    - cron: "0 23 * * *"

jobs:
  tests:
    name: Tests
    
    runs-on: ubuntu-latest
    strategy:
        matrix:
          go: ["1.17", "1.16", "1.15", "1.14", "1.13"]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.3

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Format
        run: test -z $(gofmt -l .)

      - name: Vet
        run: go vet ./...

      - name: Integration tests
        timeout-minutes: 10
        run: go test -v ./...
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
